package ing.de.software.batallanaval.logica;

public enum EnumTablero {
	AVERIADO, HUNDIDO, 
	SUBMARINO1, SUBMARINO2, SUBMARINO3, SUBMARINO4, DESTRUCTOR1, DESTRUCTOR2, DESTRUCTOR3,CRUCERO1, CRUCERO2, ACORAZADO1, 
	AGUA, FALLIDO, EXITOSO
}
